import React, { useState, useMemo } from 'react';
import { ImpactMetrics, User } from '../types';
import {
  BarChart3,
  Droplets,
  Zap,
  Coffee,
  Globe2,
  BrainCircuit,
  Loader2,
  TrendingUp,
  Award,
  Calendar,
  Sparkles,
  Info
} from 'lucide-react';
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer
} from 'recharts';
import { apiService } from '../services/apiService';
import { audioService } from '../services/audioService';
import { triggerHaptic, hapticPatterns } from '../utils/haptics';

interface Props {
  user: User;
  impact: ImpactMetrics;
}

// Generate realistic 30-day progression data for the Campus Eco Score
const generateEcoScoreHistory = () => {
  const data = [];
  const now = new Date();
  let currentScore = 1420;
  let currentStudents = 180;

  for (let i = 29; i >= 0; i--) {
    const d = new Date(now);
    d.setDate(d.getDate() - i);
    const dateStr = d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });

    // Weekend vs weekday variation
    const dayOfWeek = d.getDay();
    const isWeekend = dayOfWeek === 0 || dayOfWeek === 6;
    const dailyGrowth = isWeekend ? Math.floor(40 + Math.random() * 50) : Math.floor(110 + Math.random() * 80);

    currentScore += dailyGrowth;
    currentStudents += isWeekend ? Math.floor(Math.random() * 5) : Math.floor(10 + Math.random() * 15);

    data.push({
      date: dateStr,
      fullDate: d.toISOString().split('T')[0],
      ecoScore: currentScore,
      activeStudents: currentStudents,
      questsCompleted: Math.floor(dailyGrowth * 0.45),
      co2AvoidedKg: Math.round(dailyGrowth * 0.85)
    });
  }

  return data;
};

const fullHistoryData = generateEcoScoreHistory();

export const ImpactView: React.FC<Props> = ({ user, impact }) => {
  const [reportText, setReportText] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [timeRange, setTimeRange] = useState<'7D' | '14D' | '30D'>('30D');

  const handleGenerateReport = async () => {
    audioService.playClick();
    triggerHaptic(hapticPatterns.mediumTap);
    setIsGenerating(true);
    try {
      const res = await apiService.generateWeeklyReport();
      setReportText(res.report);
      setIsGenerating(false);
    } catch (err) {
      console.error('Report error:', err);
      setIsGenerating(false);
    }
  };

  const filteredChartData = useMemo(() => {
    if (timeRange === '7D') return fullHistoryData.slice(-7);
    if (timeRange === '14D') return fullHistoryData.slice(-14);
    return fullHistoryData;
  }, [timeRange]);

  const latestData = fullHistoryData[fullHistoryData.length - 1];
  const startData = filteredChartData[0];
  const growthPoints = latestData.ecoScore - startData.ecoScore;
  const growthPercent = (((latestData.ecoScore - startData.ecoScore) / startData.ecoScore) * 100).toFixed(1);

  return (
    <div className="space-y-6 font-sans">
      
      {/* Title & Action Header */}
      <div className="bg-slate-900/90 border border-emerald-500/30 rounded-3xl p-6 backdrop-blur-xl flex flex-col sm:flex-row justify-between sm:items-center gap-4 shadow-[0_0_30px_rgba(0,0,0,0.5)]">
        <div>
          <div className="inline-flex items-center gap-1.5 text-xs font-mono text-emerald-400 bg-emerald-950/80 px-3 py-1 rounded-full border border-emerald-500/30 uppercase mb-2">
            <BarChart3 className="w-3.5 h-3.5" /> CAMPUS SUSTAINABILITY METRICS
          </div>
          <h1 className="text-2xl font-black text-white tracking-tight">ENVIRONMENTAL IMPACT</h1>
          <p className="text-xs text-slate-400 mt-1">
            Real-time verified environmental savings generated by student quest completions across campus.
          </p>
        </div>

        <button
          onClick={handleGenerateReport}
          disabled={isGenerating}
          className="bg-gradient-to-r from-emerald-500 to-teal-400 hover:from-emerald-400 hover:to-teal-300 text-slate-950 font-black font-mono text-xs uppercase px-5 py-3 rounded-2xl shadow-[0_0_20px_rgba(16,185,129,0.4)] transition-all cursor-pointer flex items-center gap-2 shrink-0 disabled:opacity-50 active:scale-95"
        >
          {isGenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <BrainCircuit className="w-4 h-4" />}
          <span>GENERATE AI REPORT</span>
        </button>
      </div>

      {/* AI Report Section */}
      {reportText && (
        <div className="bg-slate-900 border border-emerald-500/40 rounded-3xl p-6 relative font-mono">
          <div className="flex justify-between items-center mb-3">
            <span className="text-xs text-emerald-400 font-bold flex items-center gap-1">
              <BrainCircuit className="w-4 h-4" /> AI PERSONALIZED WEEKLY REPORT
            </span>
            <button onClick={() => setReportText(null)} className="text-xs text-slate-400 hover:text-white cursor-pointer">
              DISMISS
            </button>
          </div>
          <div className="bg-slate-950 p-4 rounded-2xl border border-slate-800 text-xs text-slate-300 whitespace-pre-line leading-relaxed">
            {reportText}
          </div>
        </div>
      )}

      {/* Recharts Area Chart: 30-Day Campus Eco Score Progression */}
      <div className="bg-slate-900/90 border border-emerald-500/30 rounded-3xl p-6 backdrop-blur-xl relative overflow-hidden shadow-[0_0_30px_rgba(0,0,0,0.4)]">
        
        {/* Decorative Top Accent Light */}
        <div className="absolute -top-16 left-1/3 w-96 h-32 bg-[#16A36A]/15 rounded-full blur-3xl pointer-events-none" />

        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6 relative z-10">
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-lg font-black text-white tracking-tight flex items-center gap-2">
                CAMPUS ECO SCORE PROGRESSION
              </h2>
              <span className="text-[10px] font-mono font-bold bg-[#16A36A]/20 text-[#B8E65A] border border-[#16A36A]/50 px-2 py-0.5 rounded-full flex items-center gap-1">
                <Sparkles className="w-3 h-3" /> RECHARTS VISUALIZER
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-1">
              Cumulative eco points earned through verified energy, waste, and conservation actions over time.
            </p>
          </div>

          {/* Time Range Selector Chips */}
          <div className="flex items-center gap-1.5 bg-slate-950/80 p-1 rounded-xl border border-slate-800 self-start md:self-auto font-mono text-xs">
            {(['7D', '14D', '30D'] as const).map((range) => (
              <button
                key={range}
                onClick={() => {
                  audioService.playClick();
                  triggerHaptic(hapticPatterns.lightTap);
                  setTimeRange(range);
                }}
                className={`px-3 py-1.5 rounded-lg font-bold transition-all cursor-pointer ${
                  timeRange === range
                    ? 'bg-[#16A36A] text-slate-950 shadow-[0_0_12px_rgba(22,163,106,0.5)]'
                    : 'text-slate-400 hover:text-white'
                }`}
              >
                {range}
              </button>
            ))}
          </div>
        </div>

        {/* Score Summary Metrics Banner */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-slate-950/70 border border-slate-800/80 p-4 rounded-2xl mb-6 font-mono text-xs relative z-10">
          <div>
            <div className="text-[10px] text-slate-400 uppercase">CURRENT ECO SCORE</div>
            <div className="text-xl font-black text-[#B8E65A] mt-0.5">{latestData.ecoScore.toLocaleString()}</div>
          </div>
          <div>
            <div className="text-[10px] text-slate-400 uppercase">{timeRange} GROWTH</div>
            <div className="text-xl font-black text-emerald-400 mt-0.5 flex items-center gap-1">
              <TrendingUp className="w-4 h-4 text-emerald-400" />
              +{growthPercent}%
            </div>
          </div>
          <div>
            <div className="text-[10px] text-slate-400 uppercase">DAILY VELOCITY</div>
            <div className="text-xl font-black text-cyan-400 mt-0.5">
              +{Math.round(growthPoints / (timeRange === '7D' ? 7 : timeRange === '14D' ? 14 : 30))} pts/day
            </div>
          </div>
          <div>
            <div className="text-[10px] text-slate-400 uppercase">ACTIVE PARTICIPANTS</div>
            <div className="text-xl font-black text-purple-300 mt-0.5">{latestData.activeStudents} Students</div>
          </div>
        </div>

        {/* Recharts Area Chart Canvas */}
        <div className="w-full h-72 sm:h-80 relative z-10">
          <ResponsiveContainer width="100%" height="100%">
            <AreaChart data={filteredChartData} margin={{ top: 10, right: 10, left: -15, bottom: 0 }}>
              <defs>
                <linearGradient id="ecoScoreGrad" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#B8E65A" stopOpacity={0.6} />
                  <stop offset="95%" stopColor="#16A36A" stopOpacity={0.02} />
                </linearGradient>
                <linearGradient id="co2Grad" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#38BDF8" stopOpacity={0.4} />
                  <stop offset="95%" stopColor="#0284C7" stopOpacity={0.0} />
                </linearGradient>
              </defs>

              <CartesianGrid strokeDasharray="3 3" stroke="#1E293B" vertical={false} />

              <XAxis
                dataKey="date"
                stroke="#64748B"
                fontSize={11}
                tickLine={false}
                axisLine={{ stroke: '#334155' }}
              />

              <YAxis
                stroke="#64748B"
                fontSize={11}
                tickLine={false}
                axisLine={false}
                domain={['auto', 'auto']}
              />

              <Tooltip
                content={({ active, payload, label }) => {
                  if (active && payload && payload.length) {
                    const data = payload[0].payload;
                    return (
                      <div className="bg-slate-950/95 border border-emerald-500/50 p-3 rounded-xl shadow-2xl backdrop-blur-md font-mono text-xs space-y-1">
                        <div className="text-[#B8E65A] font-bold border-b border-slate-800 pb-1 mb-1">
                          📅 {data.fullDate} ({label})
                        </div>
                        <div className="text-white flex justify-between gap-4">
                          <span>Eco Score:</span>
                          <span className="font-bold text-[#B8E65A]">{data.ecoScore.toLocaleString()} pts</span>
                        </div>
                        <div className="text-slate-300 flex justify-between gap-4">
                          <span>Quests Done:</span>
                          <span className="font-bold text-emerald-400">{data.questsCompleted}</span>
                        </div>
                        <div className="text-slate-300 flex justify-between gap-4">
                          <span>CO₂ Avoided:</span>
                          <span className="font-bold text-cyan-400">{data.co2AvoidedKg} kg</span>
                        </div>
                      </div>
                    );
                  }
                  return null;
                }}
              />

              <Area
                type="monotone"
                dataKey="ecoScore"
                stroke="#B8E65A"
                strokeWidth={3}
                fill="url(#ecoScoreGrad)"
                dot={{ r: 3, fill: '#B8E65A', stroke: '#071A14', strokeWidth: 1.5 }}
                activeDot={{ r: 7, fill: '#B8E65A', stroke: '#071A14', strokeWidth: 3 }}
              />
            </AreaChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Impact Metric Cards Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 font-mono">
        
        {/* Plastic Saved */}
        <div className="bg-slate-900/90 border border-emerald-500/30 rounded-3xl p-6 backdrop-blur-xl relative overflow-hidden">
          <div className="p-3 rounded-2xl bg-emerald-950 text-emerald-400 border border-emerald-800 w-fit mb-4">
            <Coffee className="w-6 h-6" />
          </div>
          <div className="text-[10px] text-slate-400 uppercase">SINGLE-USE PLASTICS AVOIDED</div>
          <div className="text-3xl font-black text-white mt-1">{impact.plasticItemsAvoided.toLocaleString()}</div>
          <div className="text-[10px] text-emerald-400 mt-2">Verified in Canteen & Labs</div>
        </div>

        {/* Water Saved */}
        <div className="bg-slate-900/90 border border-cyan-500/30 rounded-3xl p-6 backdrop-blur-xl relative overflow-hidden">
          <div className="p-3 rounded-2xl bg-cyan-950 text-cyan-400 border border-cyan-800 w-fit mb-4">
            <Droplets className="w-6 h-6" />
          </div>
          <div className="text-[10px] text-slate-400 uppercase">WATER SAVED (LITERS)</div>
          <div className="text-3xl font-black text-white mt-1">{impact.waterSavedLiters.toLocaleString()} L</div>
          <div className="text-[10px] text-cyan-400 mt-2">Captured via Refill Portals</div>
        </div>

        {/* Energy Saved */}
        <div className="bg-slate-900/90 border border-amber-500/30 rounded-3xl p-6 backdrop-blur-xl relative overflow-hidden">
          <div className="p-3 rounded-2xl bg-amber-950 text-amber-400 border border-amber-800 w-fit mb-4">
            <Zap className="w-6 h-6" />
          </div>
          <div className="text-[10px] text-slate-400 uppercase">ENERGY SAVED (KWH)</div>
          <div className="text-3xl font-black text-white mt-1">{impact.energySavedKwh.toLocaleString()} kWh</div>
          <div className="text-[10px] text-amber-400 mt-2">Off-peak & Solar Raids</div>
        </div>

        {/* CO2 Offset */}
        <div className="bg-slate-900/90 border border-purple-500/30 rounded-3xl p-6 backdrop-blur-xl relative overflow-hidden">
          <div className="p-3 rounded-2xl bg-purple-950 text-purple-400 border border-purple-800 w-fit mb-4">
            <Globe2 className="w-6 h-6" />
          </div>
          <div className="text-[10px] text-slate-400 uppercase">ESTIMATED CO₂ AVOIDED</div>
          <div className="text-3xl font-black text-white mt-1">{impact.co2AvoidedKg.toLocaleString()} kg</div>
          <div className="text-[10px] text-purple-400 mt-2">Total Campus Reduction</div>
        </div>

      </div>

    </div>
  );
};
